In [0]:
from pyspark.sql import Row

In [0]:
import datetime
users = [
    {
        "id": 1,
        "first_name": "Corrie",
        "last_name": "Van den Oord",
        "email": "cvandenoord0@etsy.com",
        "phone_numbers": Row(mobile="+1 234 567 8901", home="+1 234 567 8911"),
        "courses": [1, 2],
        "is_customer": True,
        "amount_paid": 1000.55,
        "customer_from": datetime.date(2021, 1, 15),
        "last_updated_ts": datetime.datetime(2021, 2, 10, 1, 15, 0)
    },
    {
        "id": 2,
        "first_name": "Nikolaus",
        "last_name": "Brewitt",
        "email": "nbrewitt1@dailymail.co.uk",
        "phone_numbers":  Row(mobile="+1 234 567 8923", home="1 234 567 8934"),
        "courses": [3],
        "is_customer": True,
        "amount_paid": 900.0,
        "customer_from": datetime.date(2021, 2, 14),
        "last_updated_ts": datetime.datetime(2021, 2, 18, 3, 33, 0)
    },
    {
        "id": 3,
        "first_name": "Orelie",
        "last_name": "Penney",
        "email": "openney2@vistaprint.com",
        "phone_numbers": Row(mobile="+1 714 512 9752", home="+1 714 512 6601"),
        "courses": [2, 4],
        "is_customer": True,
        "amount_paid": 850.55,
        "customer_from": datetime.date(2021, 1, 21),
        "last_updated_ts": datetime.datetime(2021, 3, 15, 15, 16, 55)
    },
    {
        "id": 4,
        "first_name": "Ashby",
        "last_name": "Maddocks",
        "email": "amaddocks3@home.pl",
        "phone_numbers": Row(mobile=None, home=None),
        "courses": [],
        "is_customer": False,
        "amount_paid": None,
        "customer_from": None,
        "last_updated_ts": datetime.datetime(2021, 4, 10, 17, 45, 30)
    },
    {
        "id": 5,
        "first_name": "Kurt",
        "last_name": "Rome",
        "email": "krome4@shutterfly.com",
        "phone_numbers": Row(mobile="+1 817 934 7142", home=None),
        "courses": [],
        "is_customer": False,
        "amount_paid": None,
        "customer_from": None,
        "last_updated_ts": datetime.datetime(2021, 4, 2, 0, 55, 18)
    }
]

In [0]:
import pandas as pd

In [0]:
spark.conf.set('spark.sql.execution.arrow.pyspark.enabled',False)

In [0]:
users_df = spark.createDataFrame(pd.DataFrame(users))

In [0]:
users_df.show()

+---+----------+------------+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+
| id|first_name|   last_name|               email|       phone_numbers|courses|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+----------+------------+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+
|  1|    Corrie|Van den Oord|cvandenoord0@etsy...|{+1 234 567 8901,...| [1, 2]|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|{+1 234 567 8923,...|    [3]|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3|    Orelie|      Penney|openney2@vistapri...|{+1 714 512 9752,...| [2, 4]|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|        {null, null}|     []|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|      Kurt|        Rome|krome4@shutterfly...|{+1 817 934 7142,...|     []|      false|        NaN|         null|2021-04-02 00:55:18|
+---+----------+------------+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+

In [0]:
help(users_df.drop)

Help on method drop in module pyspark.sql.dataframe:

drop(*cols) method of pyspark.sql.dataframe.DataFrame instance
    Returns a new :class:`DataFrame` that drops the specified column.
    This is a no-op if schema doesn't contain the given column name(s).

    .. versionadded:: 1.4.0

    Parameters
    ----------
    cols: str or :class:`Column`
        a name of the column, or the :class:`Column` to drop

    Examples
    --------
    >>> df.drop('age').collect()
    [Row(name='Alice'), Row(name='Bob')]

    >>> df.drop(df.age).collect()
    [Row(name='Alice'), Row(name='Bob')]

    >>> df.join(df2, df.name == df2.name, 'inner').drop(df.name).collect()
    [Row(age=5, height=85, name='Bob')]

    >>> df.join(df2, df.name == df2.name, 'inner').drop(df2.name).collect()
    [Row(age=5, name='Bob', height=85)]

    >>> df.join(df2, 'name', 'inner').drop('age', 'height').collect()
    [Row(name='Bob')]

In [0]:
users_df.printSchema()

root
 |-- id: long (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_numbers: struct (nullable = true)
 |    |-- mobile: string (nullable = true)
 |    |-- home: string (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)
 |-- last_updated_ts: timestamp (nullable = true)

In [0]:
users_df.drop('last_updated_ts').printSchema()

root
 |-- id: long (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_numbers: struct (nullable = true)
 |    |-- mobile: string (nullable = true)
 |    |-- home: string (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)

In [0]:
users_df.drop(users_df['last_updated_ts']).printSchema()

root
 |-- id: long (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_numbers: struct (nullable = true)
 |    |-- mobile: string (nullable = true)
 |    |-- home: string (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)

In [0]:
from pyspark.sql.functions import col

In [0]:
users_df.drop(col('last_updated_ts')).printSchema()

root
 |-- id: long (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_numbers: struct (nullable = true)
 |    |-- mobile: string (nullable = true)
 |    |-- home: string (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)

If we have column name which does not exist, the column will be ignored

In [0]:
users_df.drop(col('user_id')).printSchema()

root
 |-- id: long (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- phone_numbers: struct (nullable = true)
 |    |-- mobile: string (nullable = true)
 |    |-- home: string (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)
 |-- last_updated_ts: timestamp (nullable = true)

In [0]:
users_df.drop('user_id','first_name','last_name').show()

+---+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+
| id|               email|       phone_numbers|courses|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+
|  1|cvandenoord0@etsy...|{+1 234 567 8901,...| [1, 2]|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|nbrewitt1@dailyma...|{+1 234 567 8923,...|    [3]|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3|openney2@vistapri...|{+1 714 512 9752,...| [2, 4]|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|  amaddocks3@home.pl|        {null, null}|     []|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|krome4@shutterfly...|{+1 817 934 7142,...|     []|      false|        NaN|         null|2021-04-02 00:55:18|
+---+--------------------+--------------------+-------+-----------+-----------+-------------+-------------------+

In [0]:
pii_columns = ['first_name','last_name','email','phone_numbers']

In [0]:
# This will fail
# We need to convert list to varrying arguments to get it working
#users_df_nopii = users_df.drop(pii_columns)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-4144646877334740> in <module>
      1 # This will fail
      2 # We need to convert list to varrying arguments to get it working
----> 3 users_df_nopii = users_df.drop(pii_columns)

/databricks/spark/python/pyspark/sql/dataframe.py in drop(self, *cols)
   2734                 jdf = self._jdf.drop(col._jc)
   2735             else:
-> 2736                 raise TypeError("col should be a string or a Column")
   2737         else:
   2738             for col in cols:

TypeError: col should be a string or a Column

In [0]:
users_df_nopii = users_df.drop(*pii_columns)

In [0]:
users_df_nopii.printSchema()

root
 |-- id: long (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)
 |-- last_updated_ts: timestamp (nullable = true)

In [0]:
users_df_nopii.show()

+---+-------+-----------+-----------+-------------+-------------------+
| id|courses|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+-------+-----------+-----------+-------------+-------------------+
|  1| [1, 2]|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|    [3]|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3| [2, 4]|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     []|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|     []|      false|        NaN|         null|2021-04-02 00:55:18|
+---+-------+-----------+-----------+-------------+-------------------+

In [0]:
pii_columns = ['first_name','last_name','email','phone_numbers','ssn_doesnot_exist']

In [0]:
users_df_nopii.printSchema()

root
 |-- id: long (nullable = true)
 |-- courses: array (nullable = true)
 |    |-- element: long (containsNull = true)
 |-- is_customer: boolean (nullable = true)
 |-- amount_paid: double (nullable = true)
 |-- customer_from: date (nullable = true)
 |-- last_updated_ts: timestamp (nullable = true)

In [0]:
users_df_nopii.show()

+---+-------+-----------+-----------+-------------+-------------------+
| id|courses|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+-------+-----------+-----------+-------------+-------------------+
|  1| [1, 2]|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|    [3]|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3| [2, 4]|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     []|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|     []|      false|        NaN|         null|2021-04-02 00:55:18|
+---+-------+-----------+-----------+-------------+-------------------+

Here are the features that are available with respect to dropping duplicate records.
* Drop duplicates based on all columns.It is also known as distinct.
* Drop duplicates based on certain columns.
* We can use `distinct`,`drop_duplicates` or `dropDuplicates` for these scenarios.

In [0]:
import datetime
users = [
    {
        "id": 1,
        "first_name": "Corrie",
        "last_name": "Van den Oord",
        "email": "cvandenoord0@etsy.com",
        "is_customer": True,
        "amount_paid": 1000.55,
        "customer_from": datetime.date(2021, 1, 15),
        "last_updated_ts": datetime.datetime(2021, 2, 10, 1, 15, 0)
    },
    {
        "id": 2,
        "first_name": "Nikolaus",
        "last_name": "Brewitt",
        "email": "nbrewitt1@dailymail.co.uk",
        "is_customer": True,
        "amount_paid": 900.0,
        "customer_from": datetime.date(2021, 2, 14),
        "last_updated_ts": datetime.datetime(2021, 2, 18, 3, 33, 0)
    },
    {
        "id": 3,
        "first_name": "Orelie",
        "last_name": "Penney",
        "email": "openney2@vistaprint.com",
        "is_customer": True,
        "amount_paid": 850.55,
        "customer_from": datetime.date(2021, 1, 21),
        "last_updated_ts": datetime.datetime(2021, 3, 15, 15, 16, 55)
    },
    {
        "id": 3,
        "first_name": "Orelie",
        "last_name": "Penney",
        "email": "openney2@vistaprint.com",
        "is_customer": True,
        "amount_paid": 850.55,
        "customer_from": datetime.date(2021, 1, 21),
        "last_updated_ts": datetime.datetime(2021, 3, 15, 15, 16, 55)
    },
    {
        "id": 4,
        "first_name": "Ashby",
        "last_name": "Maddocks",
        "email": "amaddocks3@home.pl",
        "is_customer": False,
        "amount_paid": None,
        "customer_from": None,
        "last_updated_ts": datetime.datetime(2021, 4, 10, 17, 45, 30)
    },
    {
        "id": 4,
        "first_name": "Ashby",
        "last_name": "Maddocks",
        "email": "amaddocks3@home.pl",
        "is_customer": False,
        "amount_paid": None,
        "customer_from": None,
        "last_updated_ts": datetime.datetime(2021, 4, 10, 17, 45, 30)
    },
    {
        "id": 5,
        "first_name": "Kurt",
        "last_name": "Rome",
        "email": "krome4@shutterfly.com",
        "is_customer": False,
        "amount_paid": None,
        "customer_from": None,
        "last_updated_ts": datetime.datetime(2021, 4, 2, 0, 55, 18)
    },
    {
        "id": 2,
        "first_name": "Nikolaus",
        "last_name": "Brewitt",
        "email": "nbrewitt1@dailymail.co.uk",
        "is_customer": True,
        "amount_paid": 1050.0,
        "customer_from": datetime.date(2021, 2, 14),
        "last_updated_ts": datetime.datetime(2021, 2, 25, 3, 33, 0)
    }
]


import pandas as pd
users_df = spark.createDataFrame(pd.DataFrame(users))

In [0]:
users_df.count()

Out[28]: 8

In [0]:
help(users_df.distinct)

Help on method distinct in module pyspark.sql.dataframe:

distinct() method of pyspark.sql.dataframe.DataFrame instance
    Returns a new :class:`DataFrame` containing the distinct rows in this :class:`DataFrame`.

    .. versionadded:: 1.3.0

    Examples
    --------
    >>> df.distinct().count()
    2

In [0]:
users_df.show()

+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
| id|first_name|   last_name|               email|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
|  1|    Corrie|Van den Oord|cvandenoord0@etsy...|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3|    Orelie|      Penney|openney2@vistapri...|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  3|    Orelie|      Penney|openney2@vistapri...|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|      false|        NaN|         null|2021-04-10 17:45:30|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|      Kurt|        Rome|krome4@shutterfly...|      false|        NaN|         null|2021-04-02 00:55:18|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|     1050.0|   2021-02-14|2021-02-25 03:33:00|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+

In [0]:
users_df.distinct().show()

+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
| id|first_name|   last_name|               email|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
|  1|    Corrie|Van den Oord|cvandenoord0@etsy...|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3|    Orelie|      Penney|openney2@vistapri...|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|      Kurt|        Rome|krome4@shutterfly...|      false|        NaN|         null|2021-04-02 00:55:18|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|     1050.0|   2021-02-14|2021-02-25 03:33:00|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+

In [0]:
users_df.distinct().count()

Out[33]: 6

In [0]:
help(users_df.drop_duplicates)

Help on method dropDuplicates in module pyspark.sql.dataframe:

dropDuplicates(subset=None) method of pyspark.sql.dataframe.DataFrame instance
    :func:`drop_duplicates` is an alias for :func:`dropDuplicates`.

    .. versionadded:: 1.4

In [0]:
help(users_df.dropDuplicates)

Help on method dropDuplicates in module pyspark.sql.dataframe:

dropDuplicates(subset=None) method of pyspark.sql.dataframe.DataFrame instance
    Return a new :class:`DataFrame` with duplicate rows removed,
    optionally only considering certain columns.

    For a static batch :class:`DataFrame`, it just drops duplicate rows. For a streaming
    :class:`DataFrame`, it will keep all data across triggers as intermediate state to drop
    duplicates rows. You can use :func:`withWatermark` to limit how late the duplicate data can
    be and system will accordingly limit the state. In addition, too late data older than
    watermark will be dropped to avoid any possibility of duplicates.

    :func:`drop_duplicates` is an alias for :func:`dropDuplicates`.

    .. versionadded:: 1.4.0

    Examples
    --------
    >>> from pyspark.sql import Row
    >>> df = sc.parallelize([ \
    ...     Row(name='Alice', age=5, height=80), \
    ...     Row(name='Alice', age=5, height=80), \
    ...     Row(name='Alice', age=10, height=80)]).toDF()
    >>> df.dropDuplicates().show()
    +-----+---+------+
    | name|age|height|
    +-----+---+------+
    |Alice|  5|    80|
    |Alice| 10|    80|
    +-----+---+------+

    >>> df.dropDuplicates(['name', 'height']).show()
    +-----+---+------+
    | name|age|height|
    +-----+---+------+
    |Alice|  5|    80|
    +-----+---+------+

In [0]:
# We can also drop duplicates based on certain columns
# This will fail as the function expects sequence type object such as list or array

users_df.dropDuplicates('id').show()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-4144646877334756> in <module>
      2 # This will fail as the function expects sequence type object such as list or array
      3
----> 4 users_df.dropDuplicates('id').show()

/databricks/spark/python/pyspark/sql/dataframe.py in dropDuplicates(self, subset)
   2125         if subset is not None and (
   2126                 not isinstance(subset, Iterable) or isinstance(subset, str)):
-> 2127             raise TypeError("Parameter 'subset' must be a list of columns")
   2128
   2129         if subset is None:

TypeError: Parameter 'subset' must be a list of columns

In [0]:
users_df.dropDuplicates(['id']).show()

+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
| id|first_name|   last_name|               email|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
|  1|    Corrie|Van den Oord|cvandenoord0@etsy...|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  3|    Orelie|      Penney|openney2@vistapri...|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|      Kurt|        Rome|krome4@shutterfly...|      false|        NaN|         null|2021-04-02 00:55:18|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+

In [0]:
users_df.dropDuplicates(['id','amount_paid']).show()

+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
| id|first_name|   last_name|               email|is_customer|amount_paid|customer_from|    last_updated_ts|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+
|  1|    Corrie|Van den Oord|cvandenoord0@etsy...|       true|    1000.55|   2021-01-15|2021-02-10 01:15:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|      900.0|   2021-02-14|2021-02-18 03:33:00|
|  2|  Nikolaus|     Brewitt|nbrewitt1@dailyma...|       true|     1050.0|   2021-02-14|2021-02-25 03:33:00|
|  3|    Orelie|      Penney|openney2@vistapri...|       true|     850.55|   2021-01-21|2021-03-15 15:16:55|
|  4|     Ashby|    Maddocks|  amaddocks3@home.pl|      false|        NaN|         null|2021-04-10 17:45:30|
|  5|      Kurt|        Rome|krome4@shutterfly...|      false|        NaN|         null|2021-04-02 00:55:18|
+---+----------+------------+--------------------+-----------+-----------+-------------+-------------------+